### ISSUE TITLE
Total for day in shell extension doesn't match overview

### ISSUE THREAD

**Issue by rrthomas** [projecthamster/hamster-shell-extension#94]
I am currently showing 5.8 hours in the widget, and 6 hours (exactly) in the overview.

**Comment by rrthomas** [comment]
Looking at this again, I see the same problem today: 6.1 hours versus 6 hours and 12 mins. I wonder whether the shell extension is only using the reported number of minutes, while underneath the applet is using seconds as well? In a day which includes already over a dozen periods of work, at an average of 30s lost per period by truncating to the number of minutes, that would easily explain the discrepancy.

**Comment by DirkHoffmann** [comment]
I see now (gnome-shell 3.32 and hamster-2.0-0.16 on Fedora 30) 4.3h in the shell extension and 4h18' in the overview (hamster application).
Therefore I beleive the bug has been fixed in the meantime.
(The display in minutes rather than decimals would be a nice enhancement, but well …)

Thanks for reporting @rrthomas, sorry for the delay in answering (though the actual reaction was there by @elbenfreund in April 2018) and hope you remain a happy hamster user.
Don't hesitate to reopen or file a new issue in case of dissatisfaction.

**Comment by DirkHoffmann** [comment]
>  (The display in minutes rather than decimals would be a nice enhancement, but well …)

Just saw that ithis is #116.

**Comment by rrthomas** [comment]
Thanks for this update! For now I'm using an old version of Hamster, and waiting until the revived legacy version is recommended for upgrade and/or (re-)appears in Ubuntu LTS.
